### ISSUE TITLE
Forecast.io Libraryy Missing

### ISSUE THREAD

**Issue by dvbit** [pnbruckner/ha-illuminance#4]
Trying to setup again the illuminance sensor

Tried via YR and WU integrations (have a key)
I keep getting this error in the log
Please note  that I do not use darksky (used in the past)

`2020-04-06 19:11:02 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/home/reinan/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 769, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/home/reinan/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/reinan/.homeassistant/custom_components/illuminance/sensor.py", line 17, in <module>
    from homeassistant.components.darksky.sensor import (
  File "/home/reinan/homeassistant/lib/python3.7/site-packages/homeassistant/components/darksky/sensor.py", line 5, in <module>
    import forecastio
ModuleNotFoundError: No module named 'forecastio'`

Running HA Core on debian

**Comment by pnbruckner** [comment]
Hmm, I probably never tested without the `darksky` integration loaded (i.e., in my configuration.)

I don't really have time to work on this now, but if you'd like to try getting it working, near the top of `/home/reinan/.homeassistant/custom_components/illuminance/sensor.py`, change these lines:
```python
from homeassistant.components.darksky.sensor import (
    ATTRIBUTION as DSS_ATTRIBUTION)
```
to:
```python
try:
    from homeassistant.components.darksky.sensor import (
        ATTRIBUTION as DSS_ATTRIBUTION)
except ImportError:
    DSS_ATTRIBUTION = "nothing"
```
and these lines:
```python
from homeassistant.components.darksky.weather import (
    ATTRIBUTION as DSW_ATTRIBUTION, MAP_CONDITION as DSW_MAP_CONDITION)
```
to:
```python
try:
    from homeassistant.components.darksky.weather import (
        ATTRIBUTION as DSW_ATTRIBUTION, MAP_CONDITION as DSW_MAP_CONDITION)
except ImportError:
    DSW_ATTRIBUTION = "nothing"
    DSW_MAP_CONDITION = {}
```
Let me know if that works for you. If it does I'll try to release a new version with this fix.

**Comment by dvbit** [comment]
Ok. Will try and let you know. Thanks for the quick answer

**Comment by dvbit** [comment]
Just tried but the python is throwing a syntax error.
I will check again.
For now I have reinstalled the darksky sensot and restored the code from github.

and it works.

**Comment by tedrock** [comment]
Just wanted to point out I'm using this without Dark Sky and I have yet to receive any errors with just Yr. I'll keep checking since by the end of the year a lot of people are probably leaving Dark Sky.

**Comment by dvbit** [comment]
Thanks. Must be something linked to other components then

Il mer 22 apr 2020, 03:21 tedrock <notifications@github.com> ha scritto:
