### ISSUE TITLE
Darksky integration removed in 2023.4.0b6 causing startup failure

### ISSUE THREAD

**Issue by erifre** [pnbruckner/ha-illuminance#40]
With Home Assistant [2023.4.0b6](https://github.com/home-assistant/core/releases/tag/2023.4.0b6) released the [Darksky integration](https://github.com/home-assistant/core/pull/90322) have been removed. This causes a failure to for this module to start.

```
Platform error: sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/illuminance/sensor.py", line 22, in <module>
    from homeassistant.components.darksky.weather import MAP_CONDITION as DSW_MAP_CONDITION
ModuleNotFoundError: No module named 'homeassistant.components.darksky'

```

Home Assistant 2023.4.0 is scheduled to be released tomorrow, on the 5th of April.

**Comment by DavidFW1960** [comment]
Same issue here. HA will not restart normally. I have to restart the container.

**Comment by pnbruckner** [comment]
@erifre @DavidFW1960 thanks! Working on a fix...

**Comment by DavidFW1960** [comment]
thanks for the fix

**Comment by pnbruckner** [comment]
@DavidFW1960 no problem. Let me know how it works for you.

**Comment by DavidFW1960** [comment]
Seems good now. Thanks again
