### ISSUE TITLE
Error loading 5.4.0 with HA 2023.12.4

### ISSUE THREAD

**Issue by hgregorian** [pnbruckner/ha-illuminance#58]
Logger: homeassistant.loader
Source: loader.py:814
First occurred: 12:51:00 AM (1 occurrences)
Last logged: 12:51:00 AM

Unexpected exception importing component custom_components.illuminance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/illuminance/__init__.py", line 25, in <module>
    from .sensor import ILLUMINANCE_SCHEMA
  File "/config/custom_components/illuminance/sensor.py", line 155, in <module>
    @dataclass(frozen=True, kw_only=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 993, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one

**Comment by hgregorian** [comment]
This issue seems to be related to https://github.com/pnbruckner/ha-illuminance/pull/56
Downgrading to 5.3.0 resolved the problem as I'm unwilling to update to 2024.1 beta at this time.

**Comment by albertoarmida** [comment]
Same issue here.

**Comment by pnbruckner** [comment]
@hgregorian @albertoarmida please try 5.4.1b0.

**Comment by albertoarmida** [comment]
Seems to be solved. Service and entity now are both available.
Thx!

**Comment by pnbruckner** [comment]
Great! I'll make a full release (i.e., 5.4.1) as that, of course, was a beta.

**Comment by pnbruckner** [comment]
Fixed by #60

**Comment by hgregorian** [comment]
Thank you!

> Fixed by #60
