### ISSUE TITLE
yr removed

### ISSUE THREAD

**Issue by SylvainGa** [pnbruckner/ha-illuminance#9]
As per 0.115.1 blog, 

The yr integration has been removed after a request from yr.no. Use the Met.no integration instead (@Danielhiversen - #39247)

This breaks this integration, although I'm not using yr myself.

```
  - platform: illuminance                                                       # Luminosité extérieur
    name: DSW Illuminance
    entity_id: weather.dark_sky
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 815, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/illuminance/sensor.py", line 19, in <module>
    from homeassistant.components.yr.sensor import ATTRIBUTION as YRS_ATTRIBUTION
ModuleNotFoundError: No module named 'homeassistant.components.yr'
```

**Comment by nkm8** [comment]
I have a PR open on this repo, but it appears to be abandoned. If you are interested, I have a few improvements to this component on my fork: https://github.com/pnbruckner/ha-illuminance/compare/master...nkm8:master

I fixed the YR issue by switching it to AccuWeather and I also added Ecobee support.

**Comment by Danielhiversen** [comment]
You can also use this custom component to get your yr sensors back: https://github.com/Danielhiversen/home_assistant_weather_data/

**Comment by jazzyisj** [comment]
> I have a PR open on this repo, but it appears to be abandoned.

I obviously can't speak for him, but I doubt Phil has abandoned this repo.  I can only imagine that with all of the work he's been doing on the HA core stuff lately he just hasn't had time to get around to updating this one.
